### ISSUE TITLE
Tracking Issue: Implementation of an Optimized Software Library

### ISSUE THREAD

**Issue by saik0** [RoaringBitmap/roaring-rs#164]
This is a tracking issue for optimizations presented by @lemire et al. in  [arXiv:1709.07821](https://arxiv.org/abs/1709.07821)

 - [x] bitset -> array (Section 3.1)
     - converting bitsets to arrays #127 
 - [ ] bitset+array (Section 3.2)
     - setting, flipping or resetting the bits of a bitset at indexes specified by an array, with and without cardinality tracking
     - branchless C equivalent #127
     - x86 asm #166 
- [x] bitset (Section 4.1.1)
    - computing the cardinality using a vectorized Harley-Seal algorithm #165
- [x] bitset+bitset (Section 4.1.2)
    - computing AND/OR/XOR/ANDNOT between two bitsets with cardinality #127 
    - using a vectorized Harley-Seal algorithm #165
- [x] array+array (Section 4.2)
    - computing the intersection between two arrays using a vectorized algorithm #163 
- [x] array+array (Section 4.3)
    - computing the union between two arrays using a vectorized algorithm #163 
- [x] array+array (Section 4.4)
    - computing the difference between two arrays using a vectorized algorithm #163 
- [x] array+array (Section 4.5)
    - computing the symmetric difference between two arrays using a vectorized algorithm #163 
- [x] fast counts (Section 5.9)
    - compute the cardinality of the result of a set operation without materializing a new bitset #167
